---
name: schema
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16', '1.15', '1.14', '1.13']
        node-version: [12.x, 13.x, 14.x]

    name: Build and test the YAML schema
    steps:
      - uses: actions/checkout@v2
      - name: setup go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: |
          go mod vendor
          yarn install

      - run: yarn run compile
      - run: yarn run schema
      - run: yarn run schemaCheck
      - run: git diff --exit-code -- schemas/*json
